<?php
__('Addons', 'theme-bs4');
__('Install Addons', 'theme-bs4');
__('Upload Addon', 'theme-bs4');
__('Update Selected', 'theme-bs4');
__('Delete Selected', 'theme-bs4');
__('Name', 'theme-bs4');
__('Description', 'theme-bs4');
__('Author', 'theme-bs4');
__('Actions', 'theme-bs4');
__('Version', 'theme-bs4');
__('Updates', 'theme-bs4');
__('All Members', 'theme-bs4');
__('Edit Member', 'theme-bs4');
__('User Details', 'theme-bs4');
__('Username', 'theme-bs4');
__('IP Address', 'theme-bs4');
__('Location', 'theme-bs4');
__('Last Logged In', 'theme-bs4');
__('Join Date', 'theme-bs4');
__('Games Played', 'theme-bs4');
__('Tournaments Played', 'theme-bs4');
__('Stakesize', 'theme-bs4');
__('Update Profile', 'theme-bs4');
__('Total Chipcount', 'theme-bs4');
__('Update Chip Count', 'theme-bs4');
__('All Tables', 'theme-bs4');
__('Create Table', 'theme-bs4');
__('Basic Settings', 'theme-bs4');
__('Detailed Settings', 'theme-bs4');
__('SMTP Settings', 'theme-bs4');
__('Currency Settings', 'theme-bs4');
__('Language Settings', 'theme-bs4');
__('Default Language', 'theme-bs4');
__('Save', 'theme-bs4');
__('How-To-Translate DIY Guide', 'theme-bs4');
__('Generate Strings', 'theme-bs4');
__('You must enter a session variable!!', 'theme-bs4');
__('Player', 'theme-bs4');
__('Filter', 'theme-bs4');
__('Report', 'theme-bs4');
__('Time', 'theme-bs4');
__('Table Styles', 'theme-bs4');
__('Install Table Style', 'theme-bs4');
__('Table Template File', 'theme-bs4');
__('New style has been added!', 'theme-bs4');
__('Themes', 'theme-bs4');
__('Install Theme', 'theme-bs4');
__('Backups', 'theme-bs4');
__('Create', 'theme-bs4');
__('Created', 'theme-bs4');
__('Size', 'theme-bs4');
__('Options', 'theme-bs4');
__('Current version', 'theme-bs4');
__('An update is available!', 'theme-bs4');
__('Make sure to keep a backup of your current files before you proceed to update.', 'theme-bs4');
__('Perform Update', 'theme-bs4');
__('Starting update...', 'theme-bs4');
__('Update Info', 'theme-bs4');
__('Close', 'theme-bs4');
__('Confirm and Proceed', 'theme-bs4');
__('Downloading update', 'theme-bs4');
__('Downloading failed!', 'theme-bs4');
__('Extracting update', 'theme-bs4');
__('Extraction complete!', 'theme-bs4');
__('Go to Homepage', 'theme-bs4');
__('Extraction failed!', 'theme-bs4');
__('No new update is available right now.', 'theme-bs4');
__('How do I change my avatar?', 'theme-bs4');
__('In the main lobby screen click the edit character link to change your avatar or upload a custom avatar. Custom avatars must be in jpg image format and less than 250kb in size.', 'theme-bs4');
__('What is the Move Timer?', 'theme-bs4');
__('The move timer ensures that smooth table play continues by auto folding or dealing hands if a player does not take their turn within the time limit set by the site administrator. If a player repeatedly fails to take their turn they will be kicked off the table and any money left in their pot will be added back on to their total bankroll.', 'theme-bs4');
__('Why did I get kicked from a game?', 'theme-bs4');
__('Players are automatically kicked if they repeadedly fail to take their turn and the game has to auto move them or if they lose connection from the table for more than the allowed time. The lengths of time are variable as they are set by the site administrator.', 'theme-bs4');
__('My player is broke, what now?', 'theme-bs4');
__('If the site administrator has enabled the option, you can renew your initial game credits by clicking the renew button on your My Player page.', 'theme-bs4');
__('How can I get my own copy of Online Poker Script v2?', 'theme-bs4');
__('Online Poker Script V2 can be purchased in two ways. You can hire your own poker table for a small annual fee or purchase the full package to install on your own website. For information about Online Poker Script V2, please visit our website:', 'theme-bs4');
__('Reset Password', 'theme-bs4');
__('Reset your Password', 'theme-bs4');
__('Email Address', 'theme-bs4');
__('Submit', 'theme-bs4');
__('Cancel', 'theme-bs4');
__('Your Username', 'theme-bs4');
__('Lobby', 'theme-bs4');
__('Table', 'theme-bs4');
__('Type', 'theme-bs4');
__('Blinds', 'theme-bs4');
__('Chat', 'theme-bs4');
__('Hide Cards', 'theme-bs4');
__('Logs', 'theme-bs4');
__('Write message', 'theme-bs4');
__('Show Cards', 'theme-bs4');
__('Rank', 'theme-bs4');
__('User', 'theme-bs4');
__('Chips', 'theme-bs4');
__('Hands Played', 'theme-bs4');
__('Hands Won', 'theme-bs4');
__('Hands Called', 'theme-bs4');
__('Hands Checked', 'theme-bs4');
__('Tournaments Won', 'theme-bs4');
__('The object of Texas Holdem is to make the best 5 card poker hand from the 5 community cards on the table and your own 2 cards that only you can see. The community cards are dealt out during the hand with betting rounds in between so you are betting on the likleyhood of forming a winning hand by the end of the hand when all cards are revealed.', 'theme-bs4');
__('A game consists of playing hands of cards and each hand is split into alternating rounds of revealing cards and betting on the results.', 'theme-bs4');
__('Your good buddy has lent you $10K to join a high stakes poker game. Whatever profit or loss you make whilst playing in a game will be added or deducted from your total bankroll whenever you leave a table. The total bankroll determines your player ranking.', 'theme-bs4');
__('Be careful not to lose the initial $10K or it\'s back to your buddy to plead for more!', 'theme-bs4');
__('Royal Flush', 'theme-bs4');
__('The highest possible poker hand is the Royal Flush. It consists of a Ten, Jack, Queen, King and Ace, all of the same suit.', 'theme-bs4');
__('Straight Flush', 'theme-bs4');
__('A combination of both a straight and a flush. The cards must all be of the same suit and they must run in value e.g. 4,5,6,7,8. If more than one player has a Straight Flush, the player with the best Highcard wins.', 'theme-bs4');
__('Four Of A Kind', 'theme-bs4');
__('This hand is made up with 4 cards of the same value (e.g. 4 X Jacks). If more than one player has Four Of A Kind the highest value Four Of A Kind would win.', 'theme-bs4');
__('Full House', 'theme-bs4');
__('This hand is made up with 3 cards of one value and two of another value e.g. 3 X Nines and 2 X Queens. If more than one player has a Full House the winning hand would be the one with the highest triple value or failing that the highest double value.', 'theme-bs4');
__('Flush', 'theme-bs4');
__('A Flush is when the hand contains 5 cards of the same suit e.g. 5 X Spades. If more than one player has a Flush the winner is the player with the best Highcard.', 'theme-bs4');
__('Straight', 'theme-bs4');
__('To make a Straight the must run in value e.g. 4,5,6,7,8 but it does not matter what suit they are. If more than one player has a Straight , the player with the best Highcard wins.', 'theme-bs4');
__('Three Of A Kind', 'theme-bs4');
__('This hand is made up with 3 cards of the same value e.g. 3 X Sevens. If more than one player has a Three Of A Kind the winning hand would be the one with the highest value Three Of A Kind.', 'theme-bs4');
__('Two Pair', 'theme-bs4');
__('Two pair of the same value e.g. 2 X Fours and 2 X Sevens. If more than one player has Two Pair, the winner is the player with the highest pair value. If both players have the same pairs the player with the best Highcard wins.', 'theme-bs4');
__('One Pair', 'theme-bs4');
__('One pair of the same value e.g. 2 X Fours. If more than one player has One Pair, the winner is the player with the highest pair value. If both players have the same pair the player with the best Highcard win.', 'theme-bs4');
__('Highcard', 'theme-bs4');
__('The Highcard is the highest value card that is in your hand that is not duplicated not a pair, 3 of a kind or 4 of a kind. If one or more players has the same Highcard the next highest Highcard will be evaluated until a winner is found.', 'theme-bs4');
__('Game Play', 'theme-bs4');
__('1. The hand begins.', 'theme-bs4');
__('2. The next player from the dealer button posts the small blind.', 'theme-bs4');
__('3. The next player posts the big blind.', 'theme-bs4');
__('4. Each player is dealt their personal hand 2 cards each. These are called the players hole cards.', 'theme-bs4');
__('5. Betting round 1 commences pre-flop.', 'theme-bs4');
__('6. The first 3 community cards are dealt out. This is called the Flop.', 'theme-bs4');
__('7. Betting round 2 commences.', 'theme-bs4');
__('8. The 4th community card is dealt out. This is called the Turn card.', 'theme-bs4');
__('9. Betting round 3 commences.', 'theme-bs4');
__('10. The 5th and last community card is dealt. This is called the River card.', 'theme-bs4');
__('11. Last betting round commences.', 'theme-bs4');
__('12. The cards of the remaining players that have not folded are turned over to find the winner.', 'theme-bs4');
__('13. The winnings are distributed**. If more than one player wins the pot is split.', 'theme-bs4');
__('14. If more than one player still has money in their pot, a new hand begins.', 'theme-bs4');
__('Note: You cannot win more than the amount you bet from another player.', 'theme-bs4');
__('Terms', 'theme-bs4');
__('Dealer Button', 'theme-bs4');
__('A chip that marks where the dealing begins. This moves forward one player each hand.', 'theme-bs4');
__('Small Blind', 'theme-bs4');
__('An automatic small bet that must be paid by the next player from the dealer button at the beginning of a hand.', 'theme-bs4');
__('Big Blind', 'theme-bs4');
__('An automatic large bet that must be paid by the next player from the small blind player at the beginning of a hand. During the first betting round this is the amount players must match or raise to stay in the current hand.', 'theme-bs4');
__('Hole Cards', 'theme-bs4');
__('The 2 cards that you are dealt as your personal hand. Other players cannot see your cards unless they turn over at the end of the hand to find the winner.', 'theme-bs4');
__('Betting Round', 'theme-bs4');
__('There are 4 betting rounds during a game. A player can choose to call a bet, raise a bet or fold their hand.', 'theme-bs4');
__('Flop', 'theme-bs4');
__('The first 3 community cards dealt out during the hand after the first betting round.', 'theme-bs4');
__('Turn', 'theme-bs4');
__('The 4th community card dealt out after the second betting round.', 'theme-bs4');
__('River', 'theme-bs4');
__('The 5th community card dealt out after the third betting round.', 'theme-bs4');
__('Call', 'theme-bs4');
__('Match the current bet amount.', 'theme-bs4');
__('Raise', 'theme-bs4');
__('Raise the current bet amount.', 'theme-bs4');
__('Fold', 'theme-bs4');
__('Discard your current hand and lose any money you have bet so far in this hand.', 'theme-bs4');
__('Allin', 'theme-bs4');
__('Bet your entire pot on the hand.', 'theme-bs4');
__('13. The winnings are distributed. If more than one player wins the pot is split.', 'theme-bs4');
__('Please Wait', 'theme-bs4');
__('Activate', 'theme-bs4');
__('Deactivate', 'theme-bs4');
__('Installed', 'theme-bs4');
__('Install Now', 'theme-bs4');
__('Settings', 'theme-bs4');
__('Update', 'theme-bs4');
__('Addon Zip File:', 'theme-bs4');
__('Download', 'theme-bs4');
__('Delete', 'theme-bs4');
__('No backups found.', 'theme-bs4');
__('Username:', 'theme-bs4');
__('Email:', 'theme-bs4');
__('IP:', 'theme-bs4');
__('Table Animations', 'theme-bs4');
__('Allow Straddle', 'theme-bs4');
__('Active', 'theme-bs4');
__('Edit', 'theme-bs4');
__('Search for members using name or email', 'theme-bs4');
__('Search', 'theme-bs4');
__('Note: If Email Approval is set, an Email Address is required.', 'theme-bs4');
__('Use with caution, this could lock you out of your system if used incorrectly.', 'theme-bs4');
__('Use SMTP', 'theme-bs4');
__('Yes', 'theme-bs4');
__('No', 'theme-bs4');
__('SMTP Host', 'theme-bs4');
__('SMTP Port', 'theme-bs4');
__('Encryption', 'theme-bs4');
__('None', 'theme-bs4');
__('SSL', 'theme-bs4');
__('TLS', 'theme-bs4');
__('TLS is not the same as STARTTLS. For most servers SSL is the recommended option.', 'theme-bs4');
__('Authentication', 'theme-bs4');
__('SMTP Username', 'theme-bs4');
__('SMTP Password', 'theme-bs4');
__('Table Name:', 'theme-bs4');
__('Table Type:', 'theme-bs4');
__('Game Style:', 'theme-bs4');
__('Min. Buyin:', 'theme-bs4');
__('Max. Buyin:', 'theme-bs4');
__('Small Blind:', 'theme-bs4');
__('Big Blind:', 'theme-bs4');
__('Style:', 'theme-bs4');
__('Activated', 'theme-bs4');
__('Theme Zip File:', 'theme-bs4');
__('Warning: these files will be updated. If you have made any changes to any of these files, you will lose your customizations.', 'theme-bs4');
__('All Rights Reserved', 'theme-bs4');
__('Welcome to', 'theme-bs4');
__('Reveal cards on Showdown', 'theme-bs4');
__('Choose whether you would like to show your cards to other players during showdown.', 'theme-bs4');
__('Check', 'theme-bs4');
__('Check/Fold', 'theme-bs4');
__('Check/Call', 'theme-bs4');
__('Bet', 'theme-bs4');
__('Start Game', 'theme-bs4');
__('Seat', 'theme-bs4');
